# logs 配置格式
# log:
#   - category:      [日志类别]
#     level:     [日志等级，可选类型为 0: unknow, 1: trace, 2: debug, 3: info, 4: warn, 5: error, 6: fatal]
#     pattern:   [日志打印格式，支持以下特殊符号：
#                   %p    日志等级
#                   %c    日志类别
#                   %f    打印日志所在的源文件名
#                   %l    打印日志所在的行号
#                   %d    打印日志时的时间
#                   %t    打印日志的线程号
#                   %F    打印日志的协程号
#                   %m    日志内容
#                   %n    换行
#                   %%    百分号
#                   %T    制表符
#                ]
#     appender:
#       - type:      [日志输出器类型，可选类型为 0 和 1， 分别对应 StdoutLogAppender, FileLogAppender]
#         file:      [日志输出的目标文件，当 type 为 FileLogAppender 时才需要提供]
#         level:     [可选配置，日志输出器的等级，若没提供则继承所在 logger 的 level]
#         pattern:   [可选配置，日志打印格式，若没提供则继承所在 logger 的 pattern]

log:
  - category: core
    level: 1
    pattern: "[%d] [%c %p] [%t:%F] [%f:%l]%T%m%n"
    appender:
      - type: 0
      - type: 1
        level: 1
        file: /var/log/server-framework/core.log
  - category: root
    level: 2
    pattern: "[%d] [%c %p] [%f]%T%m%n"
    appender:
      - type: 0
      - type: 1
        file: /var/log/server-framework/root.log

system:
  port: 8088
